### ISSUE TITLE
App crash due to non existent id

### ISSUE THREAD

**Issue by copleykj** [CollectionFS/Meteor-CollectionFS#408]
I have an app running on modulus. Everything ran relatively smoothly until I scaled it to a second servo and now all the sudden I'm getting this error and then the app instance crashes.. 

```
Error: 53fcdaea80eba4530628442f does not exist
    at /mnt/data/1/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:205:24
    at /mnt/data/1/node_modules/mongodb/lib/mongodb/cursor.js:744:35
    at Cursor.close (/mnt/data/1/node_modules/mongodb/lib/mongodb/cursor.js:969:5)
    at Cursor.nextObject (/mnt/data/1/node_modules/mongodb/lib/mongodb/cursor.js:744:17)
    at commandHandler (/mnt/data/1/node_modules/mongodb/lib/mongodb/cursor.js:713:14)
    at /mnt/data/1/node_modules/mongodb/lib/mongodb/db.js:1843:9
    at Server.Base._callHandler (/mnt/data/1/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
    at /mnt/data/1/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
    at MongoReply.parseBody (/mnt/data/1/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/mnt/data/1/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
```

**Comment by justinventuri** [comment]
We have this issue, too. Usually the app restarts without incident. However, there are times when we need to go into the db and delete all temp collections. We are using gridfs and s3.

**Comment by jimmiebtlr** [comment]
Was anything additional determined on this?  I'm also experiencing this in current versions.

**Comment by copleykj** [comment]
I would love to say that I figured this out, but unfortunately this issue caused me to move to using cloudinary.

**Comment by mxab** [comment]
do you guys use multiple nodes? As far as I know this won't work, but you can try out @rhyslbw pull request https://github.com/CollectionFS/Meteor-CollectionFS/pull/667

**Comment by neopostmodern** [comment]
The duplicate bug https://github.com/CollectionFS/Meteor-CollectionFS/issues/731 happened on my local development machine too, definitely a single node.

**Comment by ClarenceL** [comment]
Getting the same thing, Error: 55df664eebec6253187bd231 does not exist

What id is this referring to?

**Comment by derwaldgeist** [comment]
Had the same error when trying to upload more than one (server) local file to GridFS in one batch.

**Comment by MikkoA** [comment]
Same error on my local dev machine, crashes Meteor.  But after Meteor restarts, browser tries to send PUT request again and the file is uploaded properly. Any ideas on this one?

**Comment by ClarenceL** [comment]
Seems to be GridFS, use cfs:filesystem.. don't remove the GridFS package though, it seems it's still needed if you use mup to deploy

**Comment by vietnv22** [comment]
+1

**Comment by neopostmodern** [comment]
Is there any certainty that this is a GridFS level bug?
If so, this should be filed there, since it couldn't be solved here...

**Comment by vsivsi** [comment]
My package vsivsi:file-collection (a simpler alternative to CollectionFS) uses gridFS exclusively and does not have this issue. So it's unlikely to be a bug in the node.js native mongoDB gridFS support.

**Comment by louis49** [comment]
This fix works : https://github.com/welelay/Meteor-CollectionFS/commit/86939dce8bbc986e0941b385d2cd255faf95c321

**Comment by Sylox** [comment]
Thanks @louis49 but your fix didn't fix the issue. I'm still getting that error on my local development machine. What else could that be? 

This is my crash log:

    /Users/dev/.meteor/packages/cfs_gridfs/.0.0.33.qx5chu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:246
            throw message;      
                  ^
    Error: 56c8fd1f3b27fef54fc3ee72 does not exist
        at /Users/dev/.meteor/packages/cfs_gridfs/.0.0.33.qx5chu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:200:22
        at /Users/dev/.meteor/packages/cfs_gridfs/.0.0.33.qx5chu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/query.js:164:5
        at /Users/dev/.meteor/packages/cfs_gridfs/.0.0.33.qx5chu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:778:35
        at Cursor.close (/Users/dev/.meteor/packages/cfs_gridfs/.0.0.33.qx5chu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:1009:5)
        at Cursor.nextObject (/Users/dev/.meteor/packages/cfs_gridfs/.0.0.33.qx5chu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:778:17)
        at commandHandler (/Users/dev/.meteor/packages/cfs_gridfs/.0.0.33.qx5chu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:741:14)
        at /Users/dev/.meteor/packages/cfs_gridfs/.0.0.33.qx5chu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1903:9
        at Server.Base._callHandler (/Users/dev/.meteor/packages/cfs_gridfs/.0.0.33.qx5chu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
        at /Users/dev/.meteor/packages/cfs_gridfs/.0.0.33.qx5chu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
        at [object Object].MongoReply.parseBody (/Users/dev/.meteor/packages/cfs_gridfs/.0.0.33.qx5chu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)

**Comment by keyscores** [comment]
+1 Still experiencing this issue on cfs:gridfs@ 0.0.33

@aldeed would you recommend using collectionfs or vsivsi/meteor-file-collection . Is collectionfs being maintained? Thanks!

**Comment by keyscores** [comment]
Some preliminary debugging: this seems to happen when you wipe clean the gridfs tables directly on the mongodb instance.  I wiped/deleted the following tables:

cfs._tempstore.chunks
cfs.files.filerecord
cfs_gridfs._tempstore.chunks	
cfs_gridfs._tempstore.files
cfs_gridfs.filesStore.chunks	
cfs_gridfs.filesStore.files	

When I run the same operations on another new/fresh mongodb instance, I get no errors. When I switch back to the db with the wiped tables, the problem persists.

BTW my instances are hosted on compose.io.

**Comment by keyscores** [comment]
@louis49 is it possible any local filesystem caches will get stale? Perhaps collectionfs operations may be error prone because the chunks state is different on local and db? This might account for removing irrelevant temp files, causing a crash.

**Comment by louis49** [comment]
Sorry, screeching halt to work with this library is not working and has not been designed to work in multi-node. We decided to put us up for Amazon S3 that works fine.

**Comment by ScyDev** [comment]
@ChrisCinelli @aldeed Having this same problem on Google Container Engine, when running multiple containers of the Meteor app accessing the same single MongoDB instance. 

The app doesn't recover with a restart of Meteor. Deleting temp stores also didn't help. Had to restore the DB from backup.
Is there any fix or workaround that really works?

How come this is still an open issue after all this time? This makes CollectionFS completely unusable for production use.

**Comment by vsivsi** [comment]
If none of the CollectionFS collaborators are willing to maintain this package, the README should probably have this prominently noted in bold type at the top, so that new developers don't spend a lot of effort building apps around it only to discover what @ScyDev relates above.

**Comment by ScyDev** [comment]
@vsivsi That thought crossed my mind too. A big warning would be nice if a package as fundamental as this is not ready for production use.

**Comment by vsivsi** [comment]
@raix  @aldeed   Any objection to adding a "no longer being maintained" type disclaimer to the top of the README?  @ScyDev raises a legitimate point.

FYI, I continue to maintain and support `vsivsi:file-collection`, but it only provides a subset of the functionality of this package (gridFS storage with HTTP up/download support).

**Comment by ScyDev** [comment]
In our case it was actually the upload and storing of huge images that caused this problem. An image of 2.5M and roughly 4000x3000px was too much.

**Comment by ScyDev** [comment]
@vsivsi Is your `vsivsi:file-collection` package in any way a drop in replacement for gridFS? Or would it require a lot of rewriting code around the places where gridFS was used?

**Comment by vsivsi** [comment]
If you have files already stored in gridFS, file-collection will immediately work with those files. If the gridFS files were written by CollectionFS, then file metadata may have been written to the CollectionFS collection, and may need to be migrated to the `metadata` element for each file in the `.files` gridFS collection. File-collection knows nothing about the non-gridFS CollectionFS collection data.

**Comment by vsivsi** [comment]
Just to add: file-collection is built directly on gridFS, and that is the only storage backend it supports. File-collection's gridFS support is significantly more efficient and robust than that of CollectionFS.

**Comment by ScyDev** [comment]
@vsivsi Can you have a look at this? https://github.com/ScyDev/reaction/blob/development/packages/reaction-collections/common/collections/collectionFS.js

I quick-read the README on your file-collection repo. From what I've gathered there's quite a few things that I'd need to take care of. For example, having multiple stores for specific image sizes and scaling the images with graphicsmagick.

Can you see a clear picture how to implement this with file-collection, if you were in my shoes? I'm trying to guestimate if the work is worth it.

**Comment by vsivsi** [comment]
I don't have time today to review your project... But it turns out that there is a file-collection sample app that does pretty much of what you are asking about above.  https://github.com/vsivsi/meteor-file-job-sample-app

**Comment by ScyDev** [comment]
Thanks! :)

https://i.imgur.com/CuVsQty.gif

**Comment by vsivsi** [comment]
One other quick note... There's no need IMO to have separate stores to hold images of different sizes. Just use file metadata to keep track of which files are scaled to which sizes...
